runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: controller.app
  #script: helloworld_test.app

- url: /index\.html
  script: controller.app

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$


libraries:
- name: numpy
  version: "1.6.1"
- name: matplotlib
  version: "1.2.0"
